coreweave/ml-containers

- .github/workflows/gpt-neox-mpi.yml
- gpt-neox-mpi/Dockerfile
These changes add a new docker image that will be used in a kubeflow training operator example for finetuning GPT-NeoX-20B.
The Dockerfile has been used to build the image `navarrepratt/ml-containers:gpt-neox-2` which has been tested on the example code in this [kubernetes-cloud PR](https://github.com/coreweave/kubernetes-cloud/pull/131)
> feat: Add a gpt-neox image with MPI support

- sd-serializer/Dockerfile
Current serializer image only fetches the latest changes which are breaking in the newest serialization image, this fix fetches the proper commit that works for the serialization image.
> Add tensorizer commit hash to serializer image

- gpt-neox-mpi/Dockerfile
The original ElutherAI gpt-neox images used an older CUDA base image along with older versions of torch and apex. This wasn't leading to any problems at first, but I noticed that there would be a NCCL error thrown whenever a worker would run on a `g99*` A100 NVLINK 80gb node. Once I upgraded the versions I would no longer see the NCCL error on those nodes.
NCCL Error:
```
NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:825, unhandled system error, NCCL version 2.7.8
```
Two specific nodes that I know threw these errors:
- g9963e2
- g99645a
> update(gpt-neox-mpi): Update cuda and apex versions

- sd-finetuner/Dockerfile
- sd-inference/Dockerfile
- sd-serializer/Dockerfile
Adding the COMMIT ARG before the `FROM` causes the build to use the cache for all layers even when the kubernetes-cloud code has changed. This is because:
> An ARG declared before a FROM is outside of a build stage, so it can’t be used in any instruction after a FROM
- [Docker docs](https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact)
[Build from this commit pulls the new code](https://github.com/coreweave/ml-containers/actions/runs/4186926526/jobs/7256086582#step:8:239)
> fix: Move COMMIT arg into build stage

- .github/workflows/torch-base.yml
- .github/workflows/torch-nccl.yml
- torch/Dockerfile
[PyTorch 2.0](https://github.com/pytorch/pytorch/releases/tag/v2.0.0) and [torchvision 0.15](https://github.com/pytorch/vision/releases/tag/v0.15.1) officially released about 7 hours ago.
We already had builds available for the development versions, PyTorch 2.0.0-rc1 and torchvision 0.15.0-rc1, so the template for the build itself needs no changes.
> Update to PyTorch 2.0.0 and torchvision 0.15.1

- .github/workflows/torch-base.yml
- .github/workflows/torch-nccl.yml
- .github/workflows/torch.yml
- torch/Dockerfile
- This PR adds the `torchaudio` PyTorch extension library to the `torch` container build process.
- The other main PyTorch extension library, `torchvision`, was already included, but its build has been updated as well to include proper PNG/JPEG file support.
- Since the `nccl-tests` base containers now include cuDNN, `torch:nccl` builds now explicitly compile PyTorch and its extensions with cuDNN support enabled.
- A configurable compiler cache was also added in the build stage, to make the builds take slightly less of forever.
- A *15* GiB cache cuts around an hour off of build times in my testing. PyTorch recommends 25 GiB.
- It isn't known how well the GitHub Actions runner will handle it (if at all), so it's being added here starting at 1 GiB.
- This is adjustable with a `docker …
> feat(torch): Add torchaudio, cuDNN support for NCCL builds, and PNG/JPEG support for torchvision

- .github/workflows/torch.yml
Compilation target architectures 6.0, 6.1, 6.2, & 7.2 do not correspond to any GPUs currently offered by CoreWeave, and bloat the resulting builds, so they are removed as CI defaults. They can still be compiled by manually invoking a Dockerfile build.
The [list of GPU architectures currently offered by CoreWeave](https://docs.coreweave.com/coreweave-kubernetes/node-types#component-availability) are:
| GPU                 | Generation | Architecture Code | 
|---------------------|------------|-------------------| 
| `H100_NVLINK_80GB`  | Hopper     | `sm_90`           | 
| `H100_PCIE`         | Hopper     | `sm_90`           | 
| `A100_NVLINK_80GB`  | Ampere     | `sm_80`           | 
| `A100_NVLINK`       | Ampere     | `sm_80`           | 
| `A100_PCIE_40GB`    | Ampere     | `sm_80` …
> build(torch)!: Drop arches 6.0, 6.1, 6.2, & 7.2 as compilation targets

- .github/workflows/cuda-ssh.yml
- cuda-ssh/Dockerfile
This adds a container for a simple SSH server in a pod corresponding to [this documentation example](https://docs.coreweave.com/coreweave-kubernetes/examples/cuda-ssh).
Used in: [`coreweave/kubernetes-cloud/cuda-ssh`](https://github.com/coreweave/kubernetes-cloud/tree/master/cuda-ssh)
Adapted from: [docker.io/atlanticcrypto/cuda-ssh-server](https://hub.docker.com/r/atlanticcrypto/cuda-ssh-server/tags)
Its base image is `ghcr.io/coreweave/ml-containers/torch`, from this repository.
At the moment it uses the `torch:base` edition because `torch:nccl` is insuitable for SSH sessions, as its necessary environment variables don't propagate into SSH sessions. This may be switched to use `torch:nccl` as a base pending an update upstream in the …
> feat(cuda-ssh): Add CUDA SSH server container

- .github/workflows/torch-base.yml
- .github/workflows/torch-nccl.yml
Update to add CUDA 12.1.1 builds for both `torch` containers. They are added in addition to the 12.0.1 and 11.8.0 builds, and do not replace either of them.
> build(torch): Add CUDA 12.1 builds

- .github/workflows/build.yml
- .github/workflows/torch-base.yml
- .github/workflows/torch-nccl.yml
- .github/workflows/torch.yml
- torch-extras/Dockerfile
- torch-extras/compiler_wrapper.f95
This PR adds a new container named `ml-containers/torch-extras`, which is `ml-containers/torch` with supplementary libraries [DeepSpeed](https://github.com/microsoft/DeepSpeed) and [flash-attention](https://github.com/HazyResearch/flash-attention).
The code is originally based off of #21, but significantly more generalized and with the finetuner application-specific parts removed.
DeepSpeed and flash-attention both require CUDA development tools to install properly. This complicates using them with anything but an `nvidia/cuda:...-devel` based image. Optionally including them with our `ml-containers/torch` containers allows for still-lightweight images that can use those powerful libraries without the full CUDA development toolkit. It also reduces compile time for downstream Dockerfiles, …
> feat: PyTorch Extras Container

- torch-extras/Dockerfile
This change fixes a bug that prevented the `torch-extras` Dockerfile from being able to compile `flash-attn`.
Its git source directory was mounted read-only because of a missing `rw` flag on its bind mount, so it couldn't write build files.
> fix(torch-extras): Use `rw` bind mount when building `flash-attn`

- torch-extras/Dockerfile
- torch-extras/effective_cpu_count.sh
This change adds a build of [NVIDIA/apex](https://github.com/NVIDIA/apex) compiled with all possible optional extensions to the `torch-extras` container builds (#26).
It also adds a POSIX `sh` script, `effective_cpu_count.sh`, that assists in limiting concurrent compilation jobs based on [cgroups](https://man7.org/linux/man-pages/man7/cgroups.7.html) resource limits to potentially reduce compile times. This script could likely be reused for other builds as well, such as the `torch` container build.
> feat(torch-extras): Add NVIDIA Apex

- .github/workflows/torch-extras.yml
- .github/workflows/torch.yml
- torch-extras/Dockerfile
This change extracts `.github/workflows/torch-extras.yml` from `.github/workflows/torch.yml` to make it independently dispatchable.
Since `torch-extras.yml` cannot run on each push to `torch-extras/Dockerfile`, as it has no default base image to build from, a dispatchable workflow is currently necessary to build new `torch-extras` containers when a file in `torch-extras/` has been modified but nothing has changed for the base `torch` files.
This PR also fixes a bug in `torch-extras/Dockerfile` that prevented it from building correctly in daf476342951c6c19e8eace6dd755d167573fa42.
> build(torch-extras): Extract `torch-extras` workflow to be dispatchable

- torch-extras/Dockerfile
This change fixes a bug causing the `apex-downloader` step to fail while deleting unnecessary files post-downloading.
Without the `-prune` flag, the `find` call in use attempts to `rm -r` directories within already-deleted subtrees and exits with an error code despite producing correct results. With the `-prune` flag, acting on a directory instead removes its children from further `find` processing, which is correct for already-recursive commands such as `rm -r`.
> fix(torch-extras): Add `-prune` to `find` & `rm -r` Apex downloader step

- .github/workflows/torch-nccl.yml
- torch-extras/Dockerfile
This change uses the new NCCL v2.18.3 builds from [coreweave/nccl-tests PR 23](https://github.com/coreweave/nccl-tests/pull/23) in this repository's CUDA 12.0 & 12.1 builds of `torch:nccl`, updating from NCCL version 2.18.1.
> build(torch): Update base images for NCCL builds, now with NCCL v2.18.3

- README.md
This change adds an *Index* section to the README explaining the `ml-containers/torch` and `ml-containers/torch-extras` containers available.
The other containers in this repository remain undocumented for now. Since there are only two, they are written inline in the repository README, but once more are documented, the organization of this could switch to per-folder READMEs linked from the repository README.
> docs: Explain `torch` and `torch-extras` containers in the README

- .github/workflows/torch-nccl.yml
This change updates the base `nccl-tests` images used to build `torch:nccl` to versions featuring HPC-X v2.16, as introduced in coreweave/nccl-tests#25.
> build(torch): Build `nccl` images from bases with HPC-X v2.16

- .github/workflows/torch-extras.yml
This change fixes a bug that was causing `torch-extras` to sometimes build off of outdated `torch` images in our CI pipeline.
The bug was because `ghcr.io`'s implementation of the [`/v2/<package>/tags/list` registry endpoint](https://docs.docker.com/registry/spec/api/#listing-image-tags), which we use to determine the latest torch image to build from, automatically switches to paginated results unless otherwise requested once the result set is large enough, instead of only switching when requested. Since the results are ordered chronologically (oldest to newest), this means the last result—which would normally be the newest `torch` image—was not actually the newest `torch` image.
A more stable fix for this in the future would be to properly parse the paginated results, but since it …
> fix(torch-extras): Build `torch-extras` off of the most recent `torch` images

- torch/Dockerfile
This change installs `libsodium23` through `apt-get` along with other core packages. This allows supporting coreweave/tensorizer#66 encryption out of the box. The image size footprint of adding this library is under 500 KiB.
> feat(torch): Bundle `libsodium`

- .github/workflows/torch-extras.yml
- torch-extras/Dockerfile
- torch-extras/scale.sh
This change updates `flash-attention` to v2.3.6, and removes the `flash-attention` v1.0.9 builds. `xformers`'s bundled `flash-attention` is disabled so that it uses the manually built one, because `xformers`'s own `flash-attention` build currently segfaults on CUDA 12.1.
This change also adds hard limits on the number of threads used during `torch-extras` compilation jobs to avoid excessive RAM use.
> build(torch-extras): Fix `xformers` & Limit Concurrency

- hf-llm-inference/Dockerfile
This updates the source commit of the `hf-llm-inference` image to coreweave/kubernetes-cloud@cfd8b249a6bac47e0b3dab6fa2be781965a69025 to include new bug fixes.
> fix(hf-llm-inference): Update `hf-llm-inference` source commit

- tensorizer/Dockerfile
Quick adjustment to `tensorizer` Dockerfile to use a `torch-base` image and not have a `CMD` nor `ENTRYPOINT` instruction.
> fix(tensorizer): Use `torch-base` base image

- .github/workflows/build.yml
- .github/workflows/torch-extras.yml
- .github/workflows/torch-nightly.yml
This change moves all the buildcache images to their own page.
On packages that use a build cache, that tag is currently appearing at the top of the page for that image. This is causing confusion amongst users who assume the top-most tag is functionally equivalent to `:latest`. see #59.
> fix(build): move buildcache for clarity

- torch/Dockerfile
Sometimes, `apt` would semi-silently fail to fetch packages while adding the `ppa:ubuntu-toolchain-r/test` package repository, emitting a warning, but also a successful exit code. This change checks for that warning and fails the build, since it is inappropriate to continue if those packages could not be properly updated.
> build(torch): Error on timeouts while fetching packages

- .github/configurations/torch-nccl.yml
- torch/Dockerfile
This change adds [AOCL-BLAS & AOCL-LAPACK](https://www.amd.com/en/developer/aocl/dense.html) as lightweight AMD-optimized alternatives to MKL for CPU linear algebra. Previously, no BLAS or LAPACK implementations were included.
This additionally updates the `nccl-tests` base images for `torch:nccl` to use HPC-X v2.19, as added in coreweave/nccl-tests#38.
> feat(torch): Build with AOCL-BLAS and AOCL-LAPACK, and HPC-X v2.19

- .github/workflows/vllm-tensorizer.yml
- vllm-tensorizer/Dockerfile
vLLM replaced their usages of the regular `flash-attn` library with their own `vllm-flash-attn` fork in vllm-project/vllm#4686, which, as of right now, is fairly easy to compile. This change compiles it from source for compatibility with the `ml-containers/torch` base images.
This is necessary to enable updating our `vllm-tensorizer` images to include the newest versions of vLLM.
> build(vllm-tensorizer): Compile `vllm-flash-attn` from source

- .github/configurations/vllm-tensorizer.yml
- .github/workflows/vllm-tensorizer.yml
- .gitignore
- vllm-tensorizer/Dockerfile
This PR focuses on updating the vLLM version being used within the `vllm-tensorizer` Docker image and resolving the various bugs and compatibility issues that arose from this upgrade.
**Key Changes:**
- **Updated Base Image:** Switched to `ghcr.io/coreweave/ml-containers/torch-extras:es-compute-12.0-67208ca-nccl-cuda12.9.0-ubuntu22.04-nccl2.27.3-1-torch2.7.1-vision0.22.1-audio2.7.1-abi1`. This moves from `torch:base` to `torch:nccl` for CUDA development tools and aligns with PyTorch 2.7.1 and CUDA 12.9.0.
- **Upstream vLLM:** Updated vLLM source to pull from the official vllm-project/vllm.git repository (v0.9.1), rather than CoreWeave's vLLM fork
- **Build Compatibility:** Resolved various compilation errors, including:
- `FileNotFoundError: .../nvcc` and `CUDA::nvToolsExt not found` by …
> feat(vllm-tensorizer): Upgrade vLLM version and Resolve Related Build Compatibility Issues

- .github/configurations/vllm-tensorizer.yml
- vllm-tensorizer/Dockerfile
This change reverts the switch from `torch:nccl` to `torch:base` images from #101. Extra libraries are needed for vLLM from the `torch:nccl` images that are not in `torch:base`.
> build(vllm-tensorizer): Use `torch:nccl` for the final base image

- .github/configurations/vllm-tensorizer.yml
- vllm-tensorizer/Dockerfile
- vllm-tensorizer/nvcc-wrapper.py
This PR updates vLLM to its new version, along with updating its dependency `flashinfer` to match. vLLM v0.10.0 includes breaking changes, including ripping out parts of the vLLM V0 engine, so the builds from this PR branch should be given more scrutiny than other updates.
Updating `flashinfer` required changes to the compilation pipeline, as `flashinfer` v0.2.8 has issues with building for newer compute capabilities and on non-CUDA devices. In order to compile for the usual set of `ml-containers` compute capabilities (mainly the `a` variants of all modern compute capabilities), this PR copies over the `nvcc-wrapper.py` script from #102 to this container build's folder as well, and uses it to manipulate the NVCC `-gencode` flags present during the build. This would make more sense as a …
> feat(vllm-tensorizer): Update to vLLM v0.10.0 & `flashinfer` v0.2.8

- .github/configurations/vllm-tensorizer.yml
- vllm-tensorizer/Dockerfile
This change updates the `ml-containers/vllm-tensorizer` image to use vLLM v0.10.2. It also updates the bundled dependencies to match.
- A build of `NVIDIA/nixl` is now included in the container image at the path `/opt/nixl`
- The corresponding Python bindings are at the nonstandard path `/opt/nixl/lib/python3/dist-packages/nixl`, but this directory has been added to the standard system Python search path so that `import nixl` works out of the box
- The optional dependencies `deepseek-ai/DeepEP` and `perplexityai/pplx-kernels` are not currently included as they rely on rather large dependencies themselves, such as `nvshmem`, but could be added if their functionality is needed
> feat(vllm-tensorizer): Update to vLLM v0.10.2 and `flashinfer` v0.3.1
